USE PETCAREX
GO

insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6422', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2120', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1956', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0142', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8102', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2795', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6496', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0451', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4723', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9815', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2396', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5302', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0854', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7173', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6120', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9028', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1731', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0479', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9369', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6940', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4594', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2863', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2700', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2743', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4254', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5231', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7162', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7455', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5904', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2699', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1752', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7816', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2685', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3366', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3624', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9353', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7747', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2632', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2917', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8211', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9321', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6377', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3114', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1205', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5076', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1396', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6688', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4798', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2293', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2708', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1974', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8598', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4485', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3145', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1042', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1339', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1359', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1393', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8306', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5876', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8129', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6093', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7531', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3807', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1042', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6128', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7168', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1825', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3879', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6004', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5468', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6654', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5235', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6199', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1611', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2740', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2133', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3354', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2011', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2234', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6584', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6406', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6554', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6053', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4328', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2358', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7734', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4699', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3910', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7702', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5225', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9349', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9178', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5119', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5531', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1208', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1108', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0619', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4188', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1280', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8443', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5049', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1554', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7005', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4556', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8319', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8665', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5694', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2835', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2800', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0615', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2027', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2968', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6205', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5865', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2110', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6444', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2570', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4720', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4656', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4774', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0642', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0580', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6878', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5995', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0922', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8509', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3541', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7053', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0160', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1548', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0086', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8779', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1243', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9276', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1942', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7479', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3577', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1780', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3558', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3550', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3275', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1746', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7309', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8176', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3900', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6881', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0629', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3494', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1375', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1939', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2340', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0609', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3101', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4751', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5789', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5613', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0683', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4575', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4475', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4626', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0782', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8013', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3636', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9706', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5657', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4161', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1457', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8940', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4640', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4235', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4849', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8073', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4406', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9529', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9294', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1569', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1354', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4128', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1607', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1412', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9443', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7300', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3297', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9371', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3726', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8312', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6865', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4322', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5295', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0040', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5671', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7438', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2817', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8449', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5789', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0728', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4036', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4589', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7530', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2465', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4371', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5199', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2745', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6524', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2152', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9566', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0605', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6982', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4676', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8978', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2180', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3785', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5228', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4016', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4414', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1860', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5606', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7960', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6329', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0093', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1058', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0223', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4621', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3948', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2117', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8077', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5278', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5215', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5776', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6606', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2580', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1984', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6095', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4388', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0985', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3624', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0579', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2280', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0822', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3161', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5421', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7251', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7221', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8202', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4913', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7826', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8747', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2939', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5446', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7817', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1904', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8844', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8679', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6900', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6023', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2427', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8697', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2279', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0241', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2597', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0098', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3293', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1973', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7074', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5991', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1950', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5593', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1937', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5950', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6217', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4638', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5338', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3204', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5288', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7175', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7610', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1643', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0975', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5870', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2948', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9763', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9190', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1105', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6733', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2265', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4202', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1677', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8209', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3272', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2971', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4687', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1275', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7662', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7313', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6155', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6780', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0754', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7522', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5794', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1611', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2532', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5482', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4607', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1772', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7989', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1737', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7461', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8059', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6255', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4002', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9522', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5862', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1850', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4637', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0590', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3422', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7439', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5307', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8171', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8837', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6471', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3521', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2417', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2734', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7451', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2100', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7153', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9814', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2284', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5469', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1660', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4744', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3326', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9727', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0645', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0271', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4583', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8819', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0713', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2479', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4825', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7260', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3530', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7177', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8769', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9963', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8993', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5983', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0780', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5330', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4814', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8002', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5477', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8512', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7957', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4850', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9118', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7207', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0993', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3545', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7596', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2990', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4496', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4000', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7684', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2583', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8672', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6912', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4811', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9417', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9392', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4817', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5786', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6433', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5774', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1779', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('6277', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0390', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0472', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7175', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9846', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('9687', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0508', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7223', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0444', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4013', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('7279', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('1058', 'gọt móng');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4744', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2495', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0298', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2687', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3087', 'tắm');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('5010', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('4958', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('0980', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('8019', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('3629', 'cạo lông');
insert into CHAM_SOC_THU_CUNG (MA_PHIEU_DICH_VU, LOAI_DICH_VU) values ('2834', 'cạo lông');
