USE PETCAREX;
GO

-- T1. Lấy toàn bộ lịch sử khám chữa bệnh của một thú cưng cụ thể (sổ khám bệnh điện tử)
SELECT 
    TC.TEN AS TEN_THU_CUNG,
    P.THOI_GIAN_BAT_DAU AS NGAY_KHAM,
    BS.HO_TEN AS BAC_SI_PHU_TRACH,
    KB.TRIEU_CHUNG,
    KB.CHUAN_DOAN,
    ISNULL(T.THUOC, N'Không kê thuốc') AS THUOC_SU_DUNG
FROM THU_CUNG TC
JOIN PHIEU_SU_DUNG_DICH_VU P ON TC.MA_THU_CUNG = P.MA_THU_CUNG
JOIN DICH_VU_KHAM_BENH KB ON P.MA_PHIEU_DICH_VU = KB.MA_PHIEU_DICH_VU
JOIN NHAN_VIEN BS ON P.MA_NHAN_VIEN_THUC_HIEN = BS.MA_NV
LEFT JOIN THUOC_KHAM_BENH T ON KB.MA_PHIEU_DICH_VU = T.MA_PHIEU_DICH_VU
WHERE TC.MA_THU_CUNG = 'TC1'
ORDER BY P.THOI_GIAN_BAT_DAU DESC;

-- T2. Chi tiết đầy đủ 1 hóa đơn cụ thể
SELECT 
    H.MA_HOA_DON, 
    H.THOI_DIEM_LAP_HOA_DON,
    N'Sản phẩm' AS LOAI_HANG,
    SP.TEN_SAN_PHAM AS TEN_HANG,
    1 AS SO_LUONG,
    (SELECT G.GIA FROM GIA_SAN_PHAM_THEO_NAM G 
     WHERE G.TEN_SAN_PHAM = SP.TEN_SAN_PHAM 
     AND G.NAM = YEAR(H.THOI_DIEM_LAP_HOA_DON)) AS DON_GIA
FROM HOA_DON H
JOIN PHIEU_BAN_HANG PBH ON H.MA_HOA_DON = PBH.MA_HOA_DON
JOIN SAN_PHAM SP ON PBH.MA_SAN_PHAM = SP.MA_SAN_PHAM
WHERE H.MA_HOA_DON = 'HD001'
UNION ALL
SELECT 
    H.MA_HOA_DON,
    H.THOI_DIEM_LAP_HOA_DON,
    N'Dịch vụ' AS LOAI_HANG,
    DM.TEN_DICH_VU AS TEN_HANG,
    1 AS SO_LUONG,
    (SELECT G.GIA FROM GIA_DICH_VU_THEO_NAM G 
     WHERE G.LOAI_DICH_VU = DM.LOAI_DICH_VU 
     AND G.NAM = YEAR(H.THOI_DIEM_LAP_HOA_DON)) AS DON_GIA
FROM HOA_DON H
JOIN PHIEU_SU_DUNG_DICH_VU P ON H.MA_HOA_DON = P.MA_HOA_DON
JOIN DANH_MUC_DICH_VU DM ON P.LOAI_DICH_VU = DM.LOAI_DICH_VU
WHERE H.MA_HOA_DON = 'HD002';

-- T3. Truy vấn các gói tiêm của Khách hàng hết hạn chưa
SELECT 
    GT.TEN_VACCINE,
    DK.NGAY_BAT_DAU,
    DK.NGAY_KET_THUC,
    CASE 
        WHEN GETDATE() BETWEEN DK.NGAY_BAT_DAU AND DK.NGAY_KET_THUC THEN N'Đang hiệu lực'
        WHEN GETDATE() > DK.NGAY_KET_THUC THEN N'Hết hạn'
        ELSE N'Chưa kích hoạt'
    END AS TRANG_THAI
FROM KHACH_HANG_DANG_KY_GOI_TIEM KH_DK
JOIN DANG_KY_GOI_TIEM GT ON KH_DK.MA_GOI_TIEM = GT.MA_GOI_TIEM
WHERE KH_DK.MA_KHACH_HANG = '079123456789';

-- T4. Tìm chủ nhân của thú cưng 
SELECT 
    TC.TEN AS TEN_THU_CUNG,
    TC.LOAI,
    TC.GIONG,
    K.HO_TEN AS TEN_CHU,
    K.CCCD,
    SDT.SO_DIEN_THOAI,
    K.EMAIL
FROM THU_CUNG TC
JOIN KHACH K ON TC.CCCD = K.CCCD
JOIN SODIENTHOAI_KHACHHANG SDT ON K.CCCD = SDT.KHACH_HANG
WHERE TC.MA_THU_CUNG = 'TC1';

-- T5. Kiểm tra tồn kho và giá bán hiện tại của 1 sản phẩm
SELECT 
    SP.MA_SAN_PHAM,
    SP.TEN_SAN_PHAM,
    SP.HAN_SU_DUNG,
    KHO.SO_LUONG_TON_KHO,
    GIA.GIA AS GIA_HIEN_TAI
FROM SAN_PHAM SP
JOIN KHO_CHI_NHANH KHO ON SP.MA_SAN_PHAM = KHO.MA_SP
LEFT JOIN GIA_SAN_PHAM_THEO_NAM GIA ON SP.TEN_SAN_PHAM = GIA.TEN_SAN_PHAM 
    AND GIA.NAM = YEAR(GETDATE()) 
WHERE KHO.MA_CHI_NHANH = 'CN01'
  AND SP.TEN_SAN_PHAM LIKE N'%Sữa%';

-- T6. Tìm các sản phẩm sắp hết hạn sử dụng còn 1 tháng
SELECT 
    SP.TEN_SAN_PHAM,
    SP.HAN_SU_DUNG,
    KHO.MA_CHI_NHANH,
    KHO.SO_LUONG_TON_KHO
FROM SAN_PHAM SP
JOIN KHO_CHI_NHANH KHO ON SP.MA_SAN_PHAM = KHO.MA_SP
WHERE SP.HAN_SU_DUNG BETWEEN GETDATE() AND DATEADD(DAY, 30, GETDATE());

-- T7. Doanh số bán hàng của mỗi nhân viên trong tháng 
SELECT 
    NV.MA_NV,
    NV.HO_TEN,
    COUNT(DISTINCT H.MA_HOA_DON) AS SO_DON_BAN,
    SUM(H.TONG_TIEN) AS DOANH_SO_CA_NHAN
FROM NHAN_VIEN NV
JOIN HOA_DON H ON NV.MA_NV = H.MA_NHAN_VIEN
WHERE MONTH(H.THOI_DIEM_LAP_HOA_DON) = MONTH(GETDATE())
  AND YEAR(H.THOI_DIEM_LAP_HOA_DON) = YEAR(GETDATE())
GROUP BY NV.MA_NV, NV.HO_TEN
ORDER BY DOANH_SO_CA_NHAN DESC;

-- T8. Danh sách khách hàng mua nhiều nhất ở từng Chi nhánh
SELECT TOP 3 
    CN.TEN AS TEN_CHI_NHANH,
    KH.HO_TEN,
    KH.SO_DIEN_THOAI,
    SUM(H.TONG_TIEN) AS TONG_CHI_TIEU
FROM KHACH KH
JOIN SODIENTHOAI_KHACHHANG SDT ON KH.CCCD = SDT.KHACH_HANG
JOIN HOA_DON H ON KH.CCCD = H.CCCD_KHACH_HANG
JOIN NHAN_VIEN NV ON H.MA_NHAN_VIEN = NV.MA_NV
JOIN CHI_NHANH CN ON NV.CHI_NHANH_LAM_VIEC = CN.MA_CHI_NHANH
GROUP BY CN.TEN, KH.HO_TEN, KH.SO_DIEN_THOAI
ORDER BY TONG_CHI_TIEU DESC;

-- T9. Dịch vụ nào được đặt nhiều nhất theo từng quý?
SELECT 
    DATEPART(QUARTER, P.THOI_GIAN_BAT_DAU) AS QUY,
    DM.TEN_DICH_VU,
    COUNT(*) AS SO_LAN_SU_DUNG
FROM PHIEU_SU_DUNG_DICH_VU P
JOIN DANH_MUC_DICH_VU DM ON P.LOAI_DICH_VU = DM.LOAI_DICH_VU
WHERE YEAR(P.THOI_GIAN_BAT_DAU) = 2024
GROUP BY DATEPART(QUARTER, P.THOI_GIAN_BAT_DAU), DM.TEN_DICH_VU
ORDER BY QUY, SO_LAN_SU_DUNG DESC;

-- T10. Số ca khám của từng bác sĩ
SELECT 
    NV.HO_TEN AS BAC_SI,
    CN.TEN AS CHI_NHANH,
    COUNT(P.MA_PHIEU_DICH_VU) AS SO_CA_KHAM
FROM NHAN_VIEN NV
JOIN CHI_NHANH CN ON NV.CHI_NHANH_LAM_VIEC = CN.MA_CHI_NHANH
LEFT JOIN PHIEU_SU_DUNG_DICH_VU P ON NV.MA_NV = P.MA_NHAN_VIEN_THUC_HIEN
WHERE NV.CHUC_VU = 'Bac Si'
GROUP BY NV.HO_TEN, CN.TEN;

-- T11. Tìm các hóa đơn có giá trị bất thường (lỗi)
SELECT 
    H.MA_HOA_DON, 
    H.TONG_TIEN, 
    NV.HO_TEN AS NV_LAP
FROM HOA_DON H
JOIN NHAN_VIEN NV ON H.MA_NHAN_VIEN = NV.MA_NV
WHERE H.TONG_TIEN > (SELECT AVG(TONG_TIEN) * 1.5 FROM HOA_DON);

-- T12. Thống kê số lượng thú cưng theo Loài và Giống để nhập hàng
SELECT 
    LOAI, 
    GIONG, 
    COUNT(*) AS SO_LUONG_THU_CUNG
FROM THU_CUNG
GROUP BY LOAI, GIONG
ORDER BY SO_LUONG_THU_CUNG DESC;

-- T13. Khách hàng đã từng mua hàng nhưng 6 tháng rồi không quay lại
SELECT 
    K.HO_TEN, 
    K.EMAIL, 
    MAX(H.THOI_DIEM_LAP_HOA_DON) AS LAN_CUOI_MUA_HANG
FROM KHACH K
JOIN HOA_DON H ON K.CCCD = H.CCCD_KHACH_HANG
GROUP BY K.HO_TEN, K.EMAIL
HAVING MAX(H.THOI_DIEM_LAP_HOA_DON) < DATEADD(MONTH, -6, GETDATE());

-- T14. Tra cứu lịch sử chuyển chi nhánh của một nhân viên
SELECT 
    NV.HO_TEN,
    CN_CU.TEN AS CHI_NHANH_CU,
    LS.NGAY_BAT_DAU,
    LS.NGAY_KET_THUC,
    CN_HIEN_TAI.TEN AS CHI_NHANH_HIEN_TAI
FROM LICH_SU_CHUYEN_CHI_NHANH LS
JOIN NHAN_VIEN NV ON LS.MA_NHAN_VIEN = NV.MA_NV
JOIN CHI_NHANH CN_CU ON LS.MA_CHI_NHANH = CN_CU.MA_CHI_NHANH
JOIN CHI_NHANH CN_HIEN_TAI ON NV.CHI_NHANH_LAM_VIEC = CN_HIEN_TAI.MA_CHI_NHANH
WHERE NV.MA_NV = 'NV01';

-- T15. Tìm các thú cưng chưa từng được tiêm phòng
SELECT TC.TEN, TC.LOAI, K.HO_TEN AS CHU_SO_HUU, K.EMAIL
FROM THU_CUNG TC
JOIN KHACH K ON TC.CCCD = K.CCCD
WHERE NOT EXISTS (
    SELECT 1 
    FROM PHIEU_SU_DUNG_DICH_VU P
    JOIN DANH_MUC_DICH_VU DM ON P.LOAI_DICH_VU = DM.LOAI_DICH_VU
    WHERE P.MA_THU_CUNG = TC.MA_THU_CUNG 
      AND (DM.TEN_DICH_VU LIKE N'%Tiêm%' OR P.LOAI_DICH_VU = 'TP')
);

-- T16. Bảng doanh thu ngày tiền mặt và chuyển khoản
SELECT 
    THOI_DIEM_LAP_HOA_DON,
    SUM(CASE WHEN HINH_THUC_THANH_TOAN = N'Tiền mặt' THEN TONG_TIEN ELSE 0 END) AS TIEN_MAT,
    SUM(CASE WHEN HINH_THUC_THANH_TOAN != N'Tiền mặt' THEN TONG_TIEN ELSE 0 END) AS CHUYEN_KHOAN,
    SUM(TONG_TIEN) AS TONG_NGAY
FROM HOA_DON
GROUP BY THOI_DIEM_LAP_HOA_DON;

-- T17. Đánh giá chất lượng chi nhánh dựa trên Review
SELECT 
    CN.TEN AS CHI_NHANH,
    COUNT(DG.MA_DANH_GIA) AS SO_LUOT_REVIEW,
    AVG(CAST(DG.MUC_DO_HAI_LONG AS FLOAT)) AS DIEM_TB
FROM BANG_DANH_GIA DG
JOIN KHACH_HANG_SU_DUNG_CHI_NHANH KH_CN ON DG.CCCD = KH_CN.MA_KHACH_HANG
JOIN CHI_NHANH CN ON KH_CN.MA_CHI_NHANH = CN.MA_CHI_NHANH
GROUP BY CN.TEN;

-- T18. Tìm khách hàng vừa mua Thức ăn VỪA sử dụng Spa trong cùng 1 tháng
SELECT DISTINCT K.HO_TEN, K.CCCD
FROM KHACH K
JOIN HOA_DON H ON K.CCCD = H.CCCD_KHACH_HANG
WHERE H.MA_HOA_DON IN (
    SELECT PBH.MA_HOA_DON FROM PHIEU_BAN_HANG PBH 
    JOIN SAN_PHAM SP ON PBH.MA_SAN_PHAM = SP.MA_SAN_PHAM 
    WHERE SP.LOAI_SAN_PHAM = N'Thức ăn'
)
AND H.MA_HOA_DON IN (
    SELECT P.MA_HOA_DON FROM PHIEU_SU_DUNG_DICH_VU P
    JOIN DANH_MUC_DICH_VU DM ON P.LOAI_DICH_VU = DM.LOAI_DICH_VU
    WHERE DM.TEN_DICH_VU LIKE N'%Spa%'
);

-- T19. Những loại thuốc được kê đơn nhiều nhất
SELECT TOP 5 T.THUOC, COUNT(*) AS SO_LAN_KE_DON
FROM THUOC_KHAM_BENH T
GROUP BY T.THUOC
ORDER BY SO_LAN_KE_DON DESC;

-- T20. Quản lý Cửa hàng báo cáo tổng hợp cuối ngày
SELECT 
    GETDATE() AS NGAY_BAO_CAO,
    (SELECT SUM(TONG_TIEN) FROM HOA_DON WHERE THOI_DIEM_LAP_HOA_DON = CAST(GETDATE() AS DATE)) AS DOANH_THU,
    (SELECT COUNT(*) FROM HOA_DON WHERE THOI_DIEM_LAP_HOA_DON = CAST(GETDATE() AS DATE)) AS SO_DON_HANG;
GO