USE PETCAREX;
GO


CREATE OR ALTER PROCEDURE sp_DatLichKham
    @CCCD CHAR(12),
    @MaThuCung CHAR(12),
    @NgayKham DATE,
    @TrieuChung NVARCHAR(80)
AS
BEGIN
    DECLARE @MaPhieu CHAR(4) = LEFT(NEWID(), 4); 
    INSERT INTO PHIEU_SU_DUNG_DICH_VU (MA_PHIEU_DICH_VU, MA_KHACH_HANG, MA_THU_CUNG, THOI_GIAN_BAT_DAU)
    VALUES (@MaPhieu, @CCCD, @MaThuCung, @NgayKham);
    
    INSERT INTO DICH_VU_KHAM_BENH (MA_PHIEU_DICH_VU, TRIEU_CHUNG)
    VALUES (@MaPhieu, @TrieuChung);
END;
GO

-- 2. SP CHO QUẢN LÝ: Thống kê doanh thu 
CREATE OR ALTER PROCEDURE sp_BaoCaoDoanhThu
    @TuNgay DATE, @DenNgay DATE
AS
BEGIN
    SELECT 
        THOI_DIEM_LAP_HOA_DON, 
        COUNT(MA_HOA_DON) AS SO_LUONG_DON, 
        SUM(TONG_TIEN) AS TONG_DOANH_THU
    FROM HOA_DON
    WHERE THOI_DIEM_LAP_HOA_DON BETWEEN @TuNgay AND @DenNgay
    GROUP BY THOI_DIEM_LAP_HOA_DON
    ORDER BY THOI_DIEM_LAP_HOA_DON;
END;
GO

-- 3. TRIGGER: Tự động trừ tồn kho khi bán hàng
CREATE OR ALTER TRIGGER trg_TruTonKho
ON PHIEU_BAN_HANG
AFTER INSERT
AS
BEGIN
    -- Code demo logic trừ tồn kho
    DECLARE @MaSP CHAR(12);
    SELECT @MaSP = MA_SAN_PHAM FROM INSERTED;
    
    UPDATE KHO_CHI_NHANH 
    SET SO_LUONG_TON_KHO = SO_LUONG_TON_KHO - 1
    WHERE MA_SP = @MaSP;
END;
GO

